- hosts: local
  name: Create a seed node
  tags: [terraform]
  roles:
    - role: tf_seed_node
      vars:
        terraform_state: "present"

- hosts: seed
  gather_facts: false   # We may still be booting
  tags: [seed]
  pre_tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 10
        timeout: 300
    - name: Gather facts
      setup:
  roles:
    - role: seed_setup
    - role: k3sup

- hosts: local
  name: (Optional) Destroy seed node
  # Only run this when the tag is explicitly specified
  tags: [destroy, never]
  roles:
    - role: tf_seed_node
      vars:
        cluster_name: ""
        keypair_name: ""
        terraform_state: "absent"