- hosts: seed
  roles:
    - role: pre_flight
    - role: capi_deploy
      vars:  
        kubeconfig_path: "{{ management_kubeconfig_path }}"
        target_cluster_name: "{{ management_cluster_name }}"
        target_fip: "{{ management_floating_ip }}"
    - role: migrate_control_plane
    # The previous role will replacement the 'management_kubeconfig_path'
    # file with the updated copy. Re-run the deployment to ensure helm is sync'd
    - role: capi_deploy
      vars:  
        kubeconfig_path: "{{ management_kubeconfig_path }}"
        target_cluster_name: "{{ management_cluster_name }}"
        target_fip: "{{ management_floating_ip }}"
        fake_var_to_force_ansible_to_rerun_role: true
    - role: fetch_kubeconfig
      vars:
        target_cluster_name: "{{ management_cluster_name }}"

- hosts: seed
  name: (Optional) Destroy the cluster
  tags: [destroy, never]
  roles:
    - role: capi_destroy
      vars:
        target_cluster_name: "{{ management_cluster_name }}"
