- name: Set terraform to install to user's bin directory
  set_fact:
    terraform_binary_directory: "{{ ansible_user_dir }}/.local/bin"

- name: Install Terraform
  ansible.builtin.include_role: name=stackhpc.terraform.install

- name: Make Terraform project directory
  ansible.builtin.file:
    path: "{{ terraform_project_path }}"
    state: directory

- name: "Create terraform files"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ terraform_project_path }}/{{ item }}"
  with_items:
    - "resources.tf"
    - "providers.tf"

- name: Update infrastructure
  ansible.builtin.include_tasks: file=terraform_init.yml
